idf_component_register(SRCS "main.cpp"
                    "tools/room/room.cpp" 
                    "tools/switch/switch.cpp" 
                    "tools/gurup/gurup.cpp" 
                    "tools/gear/gear.cpp" 
                    "tools/instance/instance.cpp"
                    "tools/fcm/fcm.cpp"

                    INCLUDE_DIRS "."

                    )
