#ifndef _DALI_COMMAND_H
#define _DALI_COMMAND_H

#define LAMP_OFF 0x00
#define QUERY_STATUS 0x90
#define QUERY_LAMP_ON 0x93
#define QUERY_DT0 0x98
#define QUERY_DEVICE_TYPE 0x99
#define QUERY_PHYMIN_LEVEL 0x9A
#define QUERY_ACTUAL_LEVEL 0xA0
#define QUERY_MAX_LEVEL 0xA1
#define QUERY_MIN_LEVEL 0xA2
#define QUERY_POWERON_LEVEL 0xA3
#define QUERY_FAILURE_LEVEL 0xA4
#define QUERY_FADE 0xA5
#define QUERY_EXT_DEVICE_TYPE 0xA7
#define QUERY_EFADE 0xA8
#define QUERY_SCENE 0xB0
#define QUERY_GROUP_L 0xC0
#define QUERY_GROUP_H 0xC1

#define GOTO_SCENE 0x10
#define RESET 0x20
#define STORE_ACTUAL_LEVEL 0x21
#define SAVE_VARIABLE 0x22
#define SET_OPERATING_MODE 0x23
#define IDENTFY_DEVICE 0x25
#define SET_MAX_LEVEL 0x2A
#define SET_MIN_LEVEL 0x2B
#define SET_FAIL_LEVEL 0x2C
#define SET_POWERON_LEVEL 0x2D
#define SET_FADE_TIME 0x2E 
#define SET_FADE_RATE 0x2F
#define SET_EFADE_TIME 0x30

#define ADD_SCENE 0x40
#define REMOVE_SCENE 0x50
#define ADD_GROUP 0x60
#define REMOVE_GROUP 0x70

#define QUERY_COLOR_VALUE 0xFA
#define QUERY_ASSIGNED_COLOR 0xFC
#define QUERY_CHN_FEATURE 0xF9
#define ACTIVITE 0xE2
#define SET_TEMP_RGB 0xEB
#define SET_TEMP_WAF 0xEC
#define SET_TEMP_CONTROL 0xED
#define SET_CHANNEL_ASSIGN 0xF5


#define SPECIAL_SET_DTR0 0xA3

#define QUERY_CHN_FEATURE 0xF9 //Kanal Sayısı
#define QUERY_COLOR_VALUE 0xFA
   

#endif